site_name: basedpyright
site_url: https://docs.basedpyright.com
theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
    - navigation.top
    - navigation.instant
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      primary: amber
      accent: amber
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: amber
      accent: amber
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: img/favicon.ico
  logo: img/logo_black.png
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - awesome-pages
  # https://github.com/wilhelmer/mkdocs-unused-files/issues/12
  # - unused_files
  - macros:
      module_name: based_build/docs_macros
      on_undefined: strict
nav:
  - index.md
  - ... | benefits-over-pyright/**/*.md
  - ... | installation/**/*.md
  - ...
  - ... | development/**/*.md
  - ... | shoutouts.md
exclude_docs: |
  /configuration.md
repo_url: https://github.com/detachhead/basedpyright
repo_name: detachhead/basedpyright
extra_css:
  - stylesheets/extra.css
validation:
  nav:
    # using awesome-pages plugin so it doesn't recognize these:
    omitted_files: info
    absolute_links: info
  links:
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/detachhead/basedpyright
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/basedpyright/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7y9upqPrk2
