packages:
  - 'packages/*'
  - '!packages/pyright-typeserver' # not supported in basedpyright
lockfileIncludeTarballUrl: false
strictDepBuilds: false
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  pnpm: set this to true or false
  unrs-resolver: true

overrides:
  tar: '7.5.11'

minimumReleaseAgeExclude:
  - '@pnpm/exe.android-arm64@12.9.1'
  - '@pnpm/exe.android-x64@12.9.1'
  - '@pnpm/exe.darwin-arm64@12.9.1'
  - '@pnpm/exe.darwin-x64@12.9.1'
  - '@pnpm/exe.freebsd-x64@12.9.1'
  - '@pnpm/exe.linux-arm64-musl@12.9.1'
  - '@pnpm/exe.linux-arm64@12.9.1'
  - '@pnpm/exe.linux-ppc64@12.9.1'
  - '@pnpm/exe.linux-riscv64@12.9.1'
  - '@pnpm/exe.linux-s390x@12.9.1'
  - '@pnpm/exe.linux-x64-musl@12.9.1'
  - '@pnpm/exe.linux-x64@12.9.1'
  - '@pnpm/exe.win32-arm64@12.9.1'
  - '@pnpm/exe.win32-x64@12.9.1'
  - pnpm@12.9.1
