packages:
  - 'packages/*'
  - '!packages/pyright-typeserver' # not supported in basedpyright
lockfileIncludeTarballUrl: false
strictDepBuilds: false
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  unrs-resolver: true

overrides:
  tar: '7.5.11'
