name: New issue
description: A generic issue
body:
  - type: markdown
    attributes:
      value: |
        thanks for taking the time to raise an issue. please consider the following:

        - if possible, create a minimal example in [the playground](https://basedpyright.com)
        - does the issue also occur in pyright?
          - note that the default rules are different in pyright (most checks are disabled by default). for your convenience, [here is a custom pyright playground link](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&reportCallInDefaultInitializer=true&reportImplicitStringConcatenation=true&reportImplicitOverride=true&reportMissingSuperCall=true&reportPropertyTypeMismatch=true&reportShadowedImports=true&reportUnnecessaryTypeIgnoreComment=true&reportUninitializedInstanceVariable=true&reportUnreachable=true) pre-configured to match basedpyright as closely as possible.
          - if the issue does also occur in pyright, has it been [raised upstream](https://github.com/microsoft/pyright)? this isn't required, but it's useful to know if the problem has already been discussed. (also if you're lucky and your issue doesn't get rejected, chances are it will be fixed faster)
        - neovim users: i have no idea how to use neovim. while i will try my best to assist you, it would be much appreciated if you could do the following:
          - attempt to reproduce your issue in [another editor](https://docs.basedpyright.com/latest/installation/ides) to verify whether or not the problem is specific to neovim
          - if the issue is specific to neovim and you still believe it to be a basedpyright bug, provide step-by-step instructions to reproduce the issue including how you configured neovim itself and what keys to press
        - if you're reporting an issue installing basedpyright, please mention what operating system and python version you're using
        - if you're interested in fixing the issue yourself, we've tried our best to make the process to get set up for local development as easy as possible. [see the contributing instructions for more info](https://docs.basedpyright.com/latest/development/contributing/#building)
  - type: textarea
    validations:
      required: false
    attributes:
      label: Description
      description: A description of the issue
