name: 'Validation'

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GG_GITHUB_TOKEN: ${{ github.token }}

jobs:
  static_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          submodules: true # needed to typecheck mypy_primer

      - name: add gg aliases to PATH
        run: realpath ./gg >> $GITHUB_PATH

      - run: uv sync --locked

      - name: typescript typecheck
        run: pnpm run typecheck

      - name: zizmor
        # intentionally exclude workflows from the mypy_primer submodule. https://github.com/zizmorcore/zizmor/issues/784
        run: uv run zizmor .github --persona=auditor

      - run: pnpm run check

      - name: python typecheck
        run: pnpm run typecheck-python

      - name: ruff check
        run: uv run ruff check --output-format github

      - name: ruff format
        run: uv run ruff format --check --diff

      - name: pylint
        run: pnpm run pylint

      - name: validate docs
        run: uv run mkdocs build --strict

  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        id: install_python

      - run: ./gg.cmd uv sync

      # ideally we would do the same thing with ./node_modules/.bin to ensure that the version of node from nodejs-wheel
      # is always used, but it seems to be impossible to prevent github actions from using its own node version
      - name: add gg aliases to PATH (linux)
        if: runner.os != 'Windows'
        run: |
          realpath ./gg >> $GITHUB_PATH
      - name: add gg aliases to PATH (windows)
        if: runner.os == 'Windows'
        run: |
          echo (resolve-path "./gg").path | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: python tests
        run: uv run npm run test-python -- -m "not needs_all_docstubs"

      - name: npm test (pyright-internal)
        run: uv run npm test
        working-directory: packages/pyright-internal

      # TODO: all tests run in a venv now so i dont think any of this stuff is needed anymore
      - name: Create Venv
        run: |
          ${{ steps.install_python.outputs.python-path }} -m venv .venv

      - name: Activate and install pytest (linux)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          python -m pip install pytest
          python -c "import sys;print('python_venv_path=' + sys.executable)" >> $GITHUB_ENV
      - name: Activate and install pytest (windows)
        if: runner.os == 'Windows'
        run: |
          .venv\scripts\activate
          python -m pip install pytest
          python -c "import sys;print('python_venv_path=' + sys.executable)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Echo python_venv_path
        run: |
          echo python_venv_path=${{env.python_venv_path}}

      - name: Run import tests with venv
        env:
          CI_IMPORT_TEST_VENVPATH: '../../'
          CI_IMPORT_TEST_VENV: '.venv'
        run: uv run npm run test:imports
        working-directory: packages/pyright-internal

      - name: Run import tests with pythonpath
        env:
          CI_IMPORT_TEST_PYTHONPATH: ${{env.python_venv_path}}
        run: uv run npm run test:imports
        working-directory: packages/pyright-internal

  required:
    runs-on: ubuntu-latest
    name: Required
    needs:
      - static_checks
      - tests

    steps:
      - run: echo All required jobs succeeded.
